### ISSUE TITLE
Changes necessary to make it work in Python 2.7

### ISSUE THREAD

**Issue by Quasimondo** [MarcoForte/closed-form-matting#1]
Just FYI: in order to make the example run correctly in Python 2.7 there are two changes necessary to deal with the different handling of integer division:

`vals = np.eye(win_size) - (1/win_size)*(1 + np.einsum('...ij,...kj->...ik',X , winI - win_mu))
`
needs to be changed to
`vals = np.eye(win_size) - (1.0/win_size)*(1.0 + np.einsum('...ij,...kj->...ik',X , winI - win_mu))
`
and

`L = computeLaplacian(img/255)`
becomes
`L = computeLaplacian(img/255.0)`

**Comment by MarcoForte** [comment]
Thanks I'll change this now
