### ISSUE TITLE
some confuse about covariance  formular

### ISSUE THREAD

**Issue by chaomaer** [MarcoForte/closed-form-matting#11]
I have read your code. I am confused with [this line](https://github.com/MarcoForte/closed-form-matting/blob/master/closed_form_matting.py#L95), why not compute the covariance using built-in function  `np.cov` directly. Can you explain why the covariance is written this way ? thanks.

**Comment by MarcoForte** [comment]
From what I read on https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.cov.html, `np.cov` only works for 1D or 2D arrays.
