### ISSUE TITLE
If the function "compute_laplacian()" equals to cv2.Laplacian()?

### ISSUE THREAD

**Issue by Cassieyy** [MarcoForte/closed-form-matting#23]
Thanks for your brilliant work!!! I wanna know the function compute_laplacian equals to cv2.Laplacian() in OpenCV?
Looking forward to your reply!!!

**Comment by MarcoForte** [comment]
Thank you for your kind words.

The cv2.laplacian computes a different function, a kind of edge detector.  https://docs.opencv.org/3.4/d5/db5/tutorial_laplace_operator.html
