### ISSUE TITLE
float required

### ISSUE THREAD

**Issue by umsiw** [MarcoForte/closed-form-matting#8]
hi again,

i think you should make change on line 100,
this,
`vals = np.eye(win_size) - (1/win_size)*(1 + np.einsum('...ij,...kj->...ik', X, winI - win_mu))`
to this,
`vals = np.eye(win_size) - (1.0/win_size)*(1 + np.einsum('...ij,...kj->...ik', X, winI - win_mu))`

**Comment by MarcoForte** [comment]
good point for python 2.7. Feel free to submit pull requests in the future
